# Después de tirar del contenedor de producción instalamos dev-dependenciesy nuestro corredor de pruebas Mocha. 
# Finalmente, usamos nuestro corredor de prueba ( --exitespecifica un comportamiento de una versión anterior, 
# por lo que Mocha se cierra una vez que se termina). 
# El resto de este archivo debe ser casi el mismo que la versión de producción.

FROM docker_backend
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
ENV NODE_ENV dev
RUN npm install && npm install -g mocha
ARG port=80
CMD /wait && mocha test/unitTests.js --exit